In [1]:
import numpy as np

### Numpy arrays

In [5]:
l = [1, 2, 3, 4, 5]
print(type(l))
l_a = np.array(l)
print(l_a, 'Type of l_a is ', type(l_a))

<class 'list'>
[1 2 3 4 5] Type of l_a is  <class 'numpy.ndarray'>


In [9]:
l_a = l_a + 10
print(l_a)

[11 12 13 14 15]


In [10]:
l = [[1, 2, 3], [4, 5, 6]]
l_a = np.array(l)
print(l_a)

[[1 2 3]
 [4 5 6]]


In [ ]:
## 2x2x2

In [11]:
l_a.shape

(2, 3)

In [19]:
l = [[[1, 2, 3], [5, 6, 7], [9, 10, 11]], [[1, 2, 3], [5, 6, 7], [9, 10, 11]]]

In [20]:
l_a = np.array(l)

In [21]:
l_a.shape  #(2, 3, 3) # (2, ) #

(2, 3, 3)

In [15]:
print(l_a)

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]]


In [22]:
l_a.shape

(2, 3, 3)

In [23]:
l_a.size

18

In [24]:
l_a.ndim

3

In [25]:
l_a.max()

11

In [26]:
l_a.min()

1

In [27]:
np.mean(l_a)

6.0

In [28]:
l_a.shape

(2, 3, 3)

In [35]:
l_a

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]]])

In [42]:
l = [[1, 2, 3], [1, 2, 3]]

In [46]:
np.array(l).astype('float').dtype

dtype('float64')