In [2]:
import numpy as np

## Array Creation

In [4]:
# Create an array from list
l = [1, 2, 3 ,4 , 5]
l_a = np.array(l)
print(l_a, type(l_a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
l2 = [[1, 2, 3], [4, 5, 6]]
l2_a = np.array(l2)
print(l2_a, type(l2_a))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [8]:
## initialize an array with zeros
l3_a = np.zeros((3, 3))
print(l3_a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
## initialize with ones
l4_a = np.ones((3, 3))
print(l4_a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
### empty array
l5_a = np.empty((2, 3))
print(l5_a)

[[6.01433264e+175 6.93885958e+218 5.56218858e+180]
 [3.94356143e+180 4.98152401e-037 1.18784761e-075]]


In [18]:
l_0_to10 = list(range(11))
print(l_0_to10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [20]:
l7_a = np.arange(10, 20, 2) # start, end, step size
print(l7_a)

[10 12 14 16 18]


### Basic Operations

In [16]:
l6_a = l4_a + 2
print(l6_a)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [15]:
## ** is used for exponentiation
print(2**2)
print(l6_a**2)

4
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [17]:
np.sin(l6_a)

array([[0.14112001, 0.14112001, 0.14112001],
       [0.14112001, 0.14112001, 0.14112001],
       [0.14112001, 0.14112001, 0.14112001]])

In [22]:
l8_a = np.arange(1, 10).reshape(3, 3)
print(l8_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(l8_a > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [28]:
l2s = np.ones((3, 3))*2
print(l2s)
l3s = np.ones((3, 3))*3
print(l3s)
print(l2s*l3s) ## element wise multiplication of both arrays


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [29]:
print(l2s.dot(l3s)) ## dot product

[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [31]:
print(l2s@l3s) # another way to do dot product of matrices

[[18. 18. 18.]
 [18. 18. 18.]
 [18. 18. 18.]]


In [34]:
### create 3x3 matrices with all 1s, all 2s, so on , all 5s. Square them and add them

## simple list of ints
list_ints = []
for i in range(1, 6):
    list_ints.append(i)

l_matrices = []
for i in range(1, 6):
    three_by_three = np.ones((3, 3))*i
    l_matrices.append(three_by_three)
print(l_matrices)

sum_squares = np.zeros((3, 3))
for i in l_matrices:
    sum_squares = sum_squares + i*i

print(sum_squares)

[array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]]), array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]]), array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]]), array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])]
[[55. 55. 55.]
 [55. 55. 55.]
 [55. 55. 55.]]


In [36]:
l1s = np.ones((3, 3))
l1s.sum()

9.0

In [44]:
l_1 = np.arange(1, 13).reshape(4, 3)
print(l_1)
l_1.max()

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


12

### Axis

In [45]:
l_1.max(axis = 0)

array([10, 11, 12])

In [46]:
l_1.max(axis = 1)

array([ 3,  6,  9, 12])

In [47]:
l_1.sum(axis = 0)

array([22, 26, 30])

In [48]:
l_1.sum(axis = 1)

array([ 6, 15, 24, 33])

In [50]:
l_2 = np.arange(24).reshape(2, 3, 4)
print(l_2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
l_2.max(axis = 1).shape

(2, 4)

In [56]:
l_2.max(axis = 1)

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [59]:
l_2.max(axis = 2)

array([[ 3,  7, 11],
       [15, 19, 23]])

In [65]:
l_3 = np.arange(16).reshape(4, 2, 2)
print(l_3)
print('\n')
for i in l_3:
    print(i)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]
[[12 13]
 [14 15]]


In [61]:
for i in l_3.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [71]:
l_10 = np.arange(24)
print(l_10.reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Stacking

In [81]:
l1 = np.arange(3)
l2 = np.arange(3, 6)
print(l1, l2)

[0 1 2] [3 4 5]


In [83]:
np.vstack([l1, l2])

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
y = np.array([0, 1, 0, 1, 1, 1, 1, 0, 0, 1])
print(y.shape)
x = np.arange(20).reshape(10, 2)
print('x', x)
print('y', y)

(10,)
x [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
y [0 1 0 1 1 1 1 0 0 1]


In [98]:
x_0 = []
x_1 = []
index = 0
for i in x:
    if(y[index] == 0):
        x_0.append(i)
    else:
        x_1.append(i)
    index = index + 1

print('before stacking', x_0)
v_x_0 = np.vstack(x_0)
v_x_1 = np.vstack(x_1)
    
print(v_x_0,'\n\n\n', v_x_1)    

before stacking [array([0, 1]), array([4, 5]), array([14, 15]), array([16, 17])]
[[ 0  1]
 [ 4  5]
 [14 15]
 [16 17]] 


 [[ 2  3]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [18 19]]


In [100]:
h_x_0 = np.hstack([i.reshape(2, 1) for i in x_0])
print(h_x_0)

[[ 0  4 14 16]
 [ 1  5 15 17]]


In [105]:
t1 = np.arange(6).reshape(2, 3)
print(t1)
t2 = np.arange(10, 12).reshape(2, 1)
print(t2)
np.hstack([t1, t2])

[[0 1 2]
 [3 4 5]]
[[10]
 [11]]


array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 11]])

In [108]:
np.concatenate([t1, t2], axis = 1)

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 11]])

### Indexing

In [110]:
a1 = np.arange(100).reshape(2, 5 ,10)
a1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [111]:
a1[-1]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
l = [[1, 10], [2, 20]]
l[0][1]

10

In [115]:
a1[0][0][0]

0

In [116]:
a1[0, 0, 0]

0

In [119]:
print(a1)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [120]:
a1[-1, 0, -1]

59

In [123]:
a1[-2, 3, -2]
a1.shape

(2, 5, 10)

In [135]:
a1[:, 2:0:-2, :]

array([[[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]])

In [130]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [142]:
a2 = (np.arange(10)*10).reshape(2, 5)
a2

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [143]:
a2[[[0, 1], [1, 3]]]

/home/sachin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([10, 80])

In [148]:
a3 = np.arange(50).reshape(10, 5)
## index to get the following [0, 6, 12, 24]
a3[ [ [0, 1, 2, 4] , [0, 1, 2, 4]   ]    ]

/home/sachin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0,  6, 12, 24])

In [156]:
np.random.shuffle(a3)
a3

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [155]:
## argmax
a3.argmax(axis = 0)

array([4, 4, 4, 4, 4])

In [159]:
np.ones((3, 3)) == np.ones((3, 3))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [161]:
if(np.any(np.ones((3, 3)) == np.ones((3, 3)))):
    print('Equal')

Equal


In [162]:
np.isclose(0.0234567, 0.0234568, atol = 0.001)

True

In [163]:
np.ones((5, 1)).tolist()

[[1.0], [1.0], [1.0], [1.0], [1.0]]