# Numpy
Matrix manipulation

- Initializing matrix
- Random matrix
- Matrix Addition, Multiplication and Concatenation

In [1]:
import numpy as np

A = np.ones((3,2))
print(A)

A = np.zeros((3,2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
A = np.eye(3)
print(A)

A = np.diag([3,2,5])
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3 0 0]
 [0 2 0]
 [0 0 5]]


In [3]:
B = np.random.random((3,2))
print(B)

print(B.T)

[[0.51818663 0.10181439]
 [0.60535139 0.22385217]
 [0.42583155 0.52283401]]
[[0.51818663 0.60535139 0.42583155]
 [0.10181439 0.22385217 0.52283401]]


In [4]:
print(B, '\n')

print(B[0, 0])
print(B[1,0])
print(B[-1, -1])
print(B[0,:])
print(B[:,1])


[[0.51818663 0.10181439]
 [0.60535139 0.22385217]
 [0.42583155 0.52283401]] 

0.5181866262573473
0.6053513891507204
0.5228340074462274
[0.51818663 0.10181439]
[0.10181439 0.22385217 0.52283401]


## Matrix Addition
$C = A^{\intercal} + 2B$

In [5]:
A = np.ones((2,3))
B = np.random.random((3,2))
C = A.T + 2*B
print(A)
print(B)
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.05930718 0.97286376]
 [0.60612471 0.84239429]
 [0.36766332 0.17042677]]
[[1.11861436 2.94572752]
 [2.21224943 2.68478859]
 [1.73532664 1.34085354]]


## Matrix Multiplication
$C = AB$

In [6]:
C = A.dot(B)   # Dot product 
print(C)

[[1.03309521 1.98568483]
 [1.03309521 1.98568483]]


In [7]:
C = A.T * B     # Element-wise product
print(C)

[[0.05930718 0.97286376]
 [0.60612471 0.84239429]
 [0.36766332 0.17042677]]


## Matrix Concatenation
$C = [A^{\intercal},  B]$

In [8]:
print(A.T.shape, B.shape)
C = np.concatenate((A.T,B), axis=1)
D = np.concatenate((A.T,B), axis=0)
print(C)
print(D)

(3, 2) (3, 2)
[[1.         1.         0.05930718 0.97286376]
 [1.         1.         0.60612471 0.84239429]
 [1.         1.         0.36766332 0.17042677]]
[[1.         1.        ]
 [1.         1.        ]
 [1.         1.        ]
 [0.05930718 0.97286376]
 [0.60612471 0.84239429]
 [0.36766332 0.17042677]]


In [9]:
# Concatenating Vectors
a = np.ones(4)
b = np.array([2,3,4,5])
X = np.hstack([a,b])
Y = np.vstack([a,b])
print(X)
print(Y)

[1. 1. 1. 1. 2. 3. 4. 5.]
[[1. 1. 1. 1.]
 [2. 3. 4. 5.]]
